services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kuber-fe
    ports:
      - "8080:80"
    networks:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kuber-be
    restart: always
    ports:
      - "8081:3000"   # Express beží na 3000
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - backend
    env_file:
      - ./backend/.env

networks:
  backend:
    driver: bridge
