apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-be
  namespace: exam-elfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-be
  template:
    metadata:
      labels:
        app: processor-be
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: elfonator/exam-be
          ports:
            - containerPort: 3000
          env:
            - name: INPUT_DIR
              value: /input
            - name: OUTPUT_DIR
              value: /output
          volumeMounts:
            - name: processor-volume
              mountPath: /input
              subPath: input
            - name: processor-volume
              mountPath: /output
              subPath: output
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: processor-volume
          persistentVolumeClaim:
            claimName: processor-pvc
