apiVersion: v1
kind: PersistentVolume
metadata:
  name: processor-pv
  namespace: exam-elfo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/processor"

  