apiVersion: v1
kind: Service
metadata:
  name: processor-be-svc
  namespace: exam-elfo
spec:
  type: NodePort
  selector:
    app: processor-be
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30091
