apiVersion: v1
kind: Service
metadata:
  name: processor-fe-svc
  namespace: exam-elfo
spec:
  type: NodePort
  selector:
    app: processor-fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30390
